#!/bin/bash

cp net/ipv4/trickles-mod.o /lib/modules/2.4.26-gdb-trickles/
make ARCH=i386 modules_install install
make ARCH=i386 install
cp /boot/vmlinuz-2.4.26-gdb-trickles /tftpboot/vmlinuz-2.4.26-gdb-trickles-knoppix

